// leave off @2x/@3x

import getEnvVars from '../../environment'

const CLOUDINARY_ASSETS_URL = getEnvVars().CLOUDINARY_BASE_URL

const images = {
  greyClock: { uri: `${CLOUDINARY_ASSETS_URL}Icons/grey-clock.WEBP` },
  // OnBoarding

  editIcon: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/pen.WEBP` },
  onboardingOccupation: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/occupation.WEBP` },
  onboardingTime: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/onboardingTime.WEBP` },
  onboardingLocation: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/onboardingLocation.WEBP` },
  peakStream: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/peakStream.WEBP` },
  onboardingWhatToDo: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/whatToDoToday.WEBP` },
  onboardingContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_743_dklix4.WEBP` },
  planningToDo: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/planning.WEBP` },
  contactAccess: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/contactAccess.WEBP` },
  timeJar: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/timeJar.WEBP` },
  welcomeII: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/welcomeII.WEBP` },
  userWhiteBg: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/purple-person-white-bg.WEBP` },
  analogWhiteBg: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/purple-analog-white-bg.WEBP` },
  networkWhiteBg: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/purple-network-white-bg.WEBP` },
  dotsHrWhiteBg: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/purple-dots-white-bg.WEBP` },
  dotsVrtWhiteBg: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/vertical-purple-dots-white-bg.WEBP` },
  privacyII: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/privacy.WEBP` },
  starTour: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/star-tour.WEBP` },
  rgbTour: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/rgb-tour.WEBP` },
  eyeTour: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/eye-tour.WEBP` },
  errorBoundary: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/ErrorBoundary.WEBP` },
  // Welcome Screen
  info: { uri: `${CLOUDINARY_ASSETS_URL}Icons/info.WEBP` },
  backIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/backIcon.WEBP` },
  drawerIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/drawer.WEBP` },
  bellIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/notification.WEBP` },
  backWhiteIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/backWhiteIcon.WEBP` },
  globe: { uri: `${CLOUDINARY_ASSETS_URL}Icons/globe.WEBP` },
  contacts: { uri: `${CLOUDINARY_ASSETS_URL}Icons/contacts.WEBP` },
  contactsExcept: { uri: `${CLOUDINARY_ASSETS_URL}Icons/contactsExcept.WEBP` },
  specificContacts: { uri: `${CLOUDINARY_ASSETS_URL}Icons/specificContacts.WEBP` },
  onlyMe: { uri: `${CLOUDINARY_ASSETS_URL}Icons/onlyMe.WEBP` },
  lock: { uri: `${CLOUDINARY_ASSETS_URL}Icons/privacyLock.WEBP` },
  lock2: { uri: `${CLOUDINARY_ASSETS_URL}Icons/privateLockHollow.WEBP` },
  lock3: { uri: `${CLOUDINARY_ASSETS_URL}Icons/lock3.WEBP` },
  useContacts: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/useContacts.WEBP` },
  emptyMessagePicture: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/noStarredMessage.WEBP` },
  unReadChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons/unReadChat_upo5ie.WEBP` },
  starChatSwipe: { uri: `${CLOUDINARY_ASSETS_URL}Icons/StarChatSwipe_ejx81h.WEBP` },

  // Tabs
  feedIcon: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/feedIcon.png` },
  userTabIcon: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/user.png` },
  integration: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/integration.png` },
  spectrumIconTab: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/spectrumIcon.png` },
  discoverTab: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/discoverAndExplore.png` },
  chatImage: { uri: `${CLOUDINARY_ASSETS_URL}Icons/chatIcon.png` },

  carousalLeftIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/carousalLeftIcon.png` },
  carousalRightIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/carousalRightIcon.png` },

  // Other
  arrowRight: { uri: `${CLOUDINARY_ASSETS_URL}Icons/arrowRight.WEBP` },
  arrowDown: { uri: `${CLOUDINARY_ASSETS_URL}Icons/arrowDown.WEBP` },
  arrowUp: { uri: `${CLOUDINARY_ASSETS_URL}Icons/arrowUp.WEBP` },
  clear: { uri: `${CLOUDINARY_ASSETS_URL}Icons/clear.WEBP` },
  sendSMS: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendSMS.WEBP` },
  tagged: { uri: `${CLOUDINARY_ASSETS_URL}Icons/tagged.WEBP` },
  posts: { uri: `${CLOUDINARY_ASSETS_URL}Icons/posts.WEBP` },
  MyNetWork: { uri: `${CLOUDINARY_ASSETS_URL}Icons/myNetwork.WEBP` },
  arrowRightI: { uri: `${CLOUDINARY_ASSETS_URL}Icons/next_vwmifu.WEBP` },

  // Profile
  phoneIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/phone.WEBP` },
  user: { uri: `${CLOUDINARY_ASSETS_URL}Icons/user.WEBP` },
  dobIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/dob.WEBP` },
  defaultContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/defaultContact.WEBP` },
  smallTickIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/smallTickIcon.WEBP` },
  smallUserIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/smallUserIcon.WEBP` },
  verifyEmailIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/atrateIcon.png` },

  uploadIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/uploadIcon.WEBP` },
  photos: { uri: `${CLOUDINARY_ASSETS_URL}photos.WEBP` },
  audioTrack: { uri: `${CLOUDINARY_ASSETS_URL}Icons/audioTrack.WEBP` },
  audioPlay: { uri: `${CLOUDINARY_ASSETS_URL}Icons/audioPlay.WEBP` },

  boxCrossIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/boxCrossIcon.WEBP` },
  reportIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/reportIcon.WEBP` },
  settingBoxIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/settingIcon.WEBP` },
  clockBoxIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/clockIcon.WEBP` },
  importCalender: { uri: `${CLOUDINARY_ASSETS_URL}Icons/importCalender.WEBP` },
  integrationIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/skill-development_1_ejoyde.WEBP` },

  // Timer
  time: { uri: `${CLOUDINARY_ASSETS_URL}Timer/time.WEBP` },
  date: { uri: `${CLOUDINARY_ASSETS_URL}Timer/month.WEBP` },
  year: { uri: `${CLOUDINARY_ASSETS_URL}Timer/year.WEBP` },
  day: { uri: `${CLOUDINARY_ASSETS_URL}Timer/day.WEBP` },
  calendar: { uri: `${CLOUDINARY_ASSETS_URL}Timer/calendarIcon.WEBP` },
  clock: { uri: `${CLOUDINARY_ASSETS_URL}Timer/clockIcon.WEBP` },
  stop: { uri: `${CLOUDINARY_ASSETS_URL}Timer/stopIcon.WEBP` },

  // stopwatch
  stopwatchTime: { uri: `${CLOUDINARY_ASSETS_URL}stopwatch/time.WEBP` },
  stopwatchClock: { uri: `${CLOUDINARY_ASSETS_URL}stopwatch/clock.WEBP` },

  notification: { uri: `${CLOUDINARY_ASSETS_URL}notification.WEBP` },
  post: { uri: `${CLOUDINARY_ASSETS_URL}post.WEBP` },

  // Birthday
  birthday: { uri: `${CLOUDINARY_ASSETS_URL}Icons/image_12_miknse.WEBP` },
  birthdayIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/birthday-cake_1_b9vwsx.WEBP` },
  weatherApiIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/weatherApi_wxdqzj.WEBP` },
  airQualityIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/airQuality_rtpdzz.WEBP` },

  sendMessageII: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendMessageII.png` },
  locationMap: { uri: `${CLOUDINARY_ASSETS_URL}map.WEBP` },
  like: { uri: `${CLOUDINARY_ASSETS_URL}Icons/like.WEBP` },
  likeFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons/likeFilled.WEBP` },
  message: { uri: `${CLOUDINARY_ASSETS_URL}Icons/comment.WEBP` },
  heart: { uri: `${CLOUDINARY_ASSETS_URL}Icons/heart.WEBP` },
  heartFill: { uri: `${CLOUDINARY_ASSETS_URL}Icons/heart_fill.WEBP` },
  sendMessage: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendMessage.WEBP` },
  share: { uri: `${CLOUDINARY_ASSETS_URL}Icons/share.WEBP` },
  repeat: { uri: `${CLOUDINARY_ASSETS_URL}Icons/repeat.WEBP` },
  repeatII: { uri: `${CLOUDINARY_ASSETS_URL}Icons/repeatII.WEBP` },
  crossIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/crossIcon.WEBP` },
  cameraSwitch: { uri: `${CLOUDINARY_ASSETS_URL}Icons/cameraSwitch.WEBP` },
  notificationIcon: { uri: `${CLOUDINARY_ASSETS_URL}notificationIcon.WEBP` },
  emptyImage: require('../images/defaultIcons/emptyImage.png'),
  horizontalDots: require('../images/defaultIcons/horizontalDots.png'),
  shareProfile: require('../images/defaultIcons/shareProfile.png'),
  emailOutline: require('../images/defaultIcons/emailOutline.png'),
  feedTabIcon: require('../images/defaultIcons/feedTabIcon.png'),
  interests: require('../images/defaultIcons/interests.png'),
  interestsPink: require('../images/defaultIcons/interestsPink.png'),
  locationPermission: require('../images/defaultIcons/locationPermission.png'),
  contactsPermission: require('../images/defaultIcons/contactsPermission.png'),
  notificationPermission: require('../images/defaultIcons/notificationPermission.png'),
  IPhoneAlertNone: { uri: `${CLOUDINARY_ASSETS_URL}iPhoneAlertNone.WEBP` },
  IPhoneAlert: { uri: `${CLOUDINARY_ASSETS_URL}iPhoneFrontAlert.WEBP` },
  IPhoneBanner: { uri: `${CLOUDINARY_ASSETS_URL}iPhoneFrontBanner.WEBP` },
  removeNotification: { uri: `${CLOUDINARY_ASSETS_URL}Icons/removeNotification.WEBP` },
  timeFormat: { uri: `${CLOUDINARY_ASSETS_URL}timezone.WEBP` },
  archiveCirlce: { uri: `${CLOUDINARY_ASSETS_URL}Icons/archiveCirlce.WEBP` },
  exclamation: { uri: `${CLOUDINARY_ASSETS_URL}Icons/exclamation.WEBP` },
  exclamation2: { uri: `${CLOUDINARY_ASSETS_URL}Icons/exclamation2.WEBP` },
  createAnalogAlert: { uri: `${CLOUDINARY_ASSETS_URL}Icons/createAnalogAlert.WEBP` },
  sadFace: { uri: `${CLOUDINARY_ASSETS_URL}sadFace.WEBP` },
  myAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/myAnalogs.WEBP` },
  taggedAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/taggedAnalogs.WEBP` },
  cross: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/cross.WEBP` },
  crossII: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/crossII.WEBP` },
  combinedAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/combinedAnalogs.WEBP` },
  checked: { uri: `${CLOUDINARY_ASSETS_URL}Icons/checked.WEBP` },
  taggedConnections: { uri: `${CLOUDINARY_ASSETS_URL}Icons/taggedConnections.WEBP` },
  search: { uri: `${CLOUDINARY_ASSETS_URL}Icons/search.WEBP` },
  imageIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/imageIcon.WEBP` },
  playAudio: { uri: `${CLOUDINARY_ASSETS_URL}Icons/playAudio.WEBP` },
  playVideo: { uri: `${CLOUDINARY_ASSETS_URL}Icons/playVideo.WEBP` },
  arrowRightSmall: { uri: `${CLOUDINARY_ASSETS_URL}Icons/smallArrowRight.WEBP` },
  camera: { uri: `${CLOUDINARY_ASSETS_URL}Icons/camera.WEBP` },
  gallery: { uri: `${CLOUDINARY_ASSETS_URL}Icons/gallary.WEBP` },
  gif: { uri: `${CLOUDINARY_ASSETS_URL}Icons/gif.WEBP` },
  taggedUser: { uri: `${CLOUDINARY_ASSETS_URL}Icons/userTagged.WEBP` },
  spectrum: { uri: `${CLOUDINARY_ASSETS_URL}Icons/spectrum.png` },
  cliquesIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/cliquesIcon.WEBP` },
  chatIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/chatIcon.WEBP` },
  sendChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/sendMessage.WEBP` },
  crossCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/crossCirlce.WEBP` },
  personalMessage: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/message.WEBP` },
  hashTags: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/hashtags_tghcwk.WEBP` },
  analogSearch: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/analogSearch_oyewhz.WEBP` },
  chatUserImage: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/dummyChatImage_a09zvq.WEBP` },

  // Connection Options Icons
  blockConnection: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/blockConnection.WEBP` },
  removeConnection: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/removeConnection.WEBP` },
  shareConnection: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/shareConnection.WEBP` },

  // Add Analog
  add: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/add.WEBP` },
  stopTime: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/stopTimer.WEBP` },

  // Contact
  downloadContacts: { uri: `${CLOUDINARY_ASSETS_URL}contacts/downloadContacts.WEBP` },
  appleCalendar: { uri: `${CLOUDINARY_ASSETS_URL}contacts/appleCalendar.WEBP` },
  appleReminder: { uri: `${CLOUDINARY_ASSETS_URL}contacts/appleReminder.WEBP` },
  Google: { uri: `${CLOUDINARY_ASSETS_URL}contacts/calendar.WEBP` },
  evernote: { uri: `${CLOUDINARY_ASSETS_URL}contacts/evernote.WEBP` },
  microsoft: { uri: `${CLOUDINARY_ASSETS_URL}contacts/microsoft.WEBP` },
  microsoftII: { uri: `${CLOUDINARY_ASSETS_URL}contacts/microsoftII.WEBP` },
  Outlook: { uri: `${CLOUDINARY_ASSETS_URL}contacts/outlook.WEBP` },
  facebook: { uri: `${CLOUDINARY_ASSETS_URL}contacts/facebook.WEBP` },
  gmail: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/gmail.WEBP` },
  phoneContacts: { uri: `${CLOUDINARY_ASSETS_URL}contacts/phoneContacts.WEBP` },

  // Register
  analog: { uri: `${CLOUDINARY_ASSETS_URL}Register/analog.WEBP` },
  facebookIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/facebook.WEBP` },
  googleIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/google.WEBP` },
  linkedInIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/linkedin.WEBP` },
  microsoftIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/microsoft.WEBP` },
  outlookIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/outlook.WEBP` },
  phoneRegisterIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/phone.WEBP` },
  AppleIcon: { uri: `${CLOUDINARY_ASSETS_URL}Register/appleIcon.WEBP` },

  // Calendar
  mapIcon: { uri: `${CLOUDINARY_ASSETS_URL}Calendar/map.WEBP` },
  mapDefaultIcon: { uri: `${CLOUDINARY_ASSETS_URL}mapIcon.WEBP` },
  directionsIcon: { uri: `${CLOUDINARY_ASSETS_URL}directionsIcon.WEBP` },
  friendsIcon: { uri: `${CLOUDINARY_ASSETS_URL}Calendar/friends.WEBP` },
  calendarIcon: { uri: `${CLOUDINARY_ASSETS_URL}Calendar/calendar.WEBP` },

  // Analog Actions
  archive: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/archive.WEBP` },
  block: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/block.WEBP` },
  complete: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/completeIcon1.WEBP` },
  resetIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/resetIcon.WEBP` },
  delete: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/delete.WEBP` },
  edit: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/edit.WEBP` },
  duplicatePost: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/duplicate.WEBP` },
  hide: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/hide.WEBP` },
  save: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/save.WEBP` },
  snooze: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/snooze.WEBP` },
  createAnalog: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/createAnalog.WEBP` },
  savedPosts: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/savedPosts.WEBP` },
  taggedPosts: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/taggedPosts.WEBP` },
  bookmark: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/bookmark.WEBP` },
  repeatIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/repeatIcon.WEBP` },
  turnOffCommenting: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/turnOffCommenting.WEBP` },
  addMoreTime: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/addMoreTime.WEBP` },
  tourImage: { uri: `${CLOUDINARY_ASSETS_URL}AnalogActions/tourIcon.WEBP` },

  // Side Menu
  streams: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/streams.WEBP` },
  helpIcon: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/help.WEBP` },
  account: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/user.WEBP` },
  setting: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/setting.WEBP` },
  download: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/download.WEBP` },
  infoIcon: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/information.WEBP` },
  quickTour: { uri: `${CLOUDINARY_ASSETS_URL}SideMenu/compass.WEBP` },

  // new drawer icons
  createBusiness: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/createbusiness.WEBP` },
  drawerMyNetwork: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/mynetwork.WEBP` },
  drawerCalender: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/calender.WEBP` },
  analogDeleted: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/analogDeleted_bmbhnn.WEBP` },
  deletedAnalog: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/deletedAnalog_mygxku.WEBP` },
  analogLogo: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/analog-logo.WEBP` },
  saveII: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/saveII.WEBP` },
  saveIII: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/saveIII.WEBP` },
  saveIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/saveIV.WEBP` },
  savePinkFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/saved-filled.WEBP` },

  // Animations

  // Discover Screen
  discoverSearch: { uri: `${CLOUDINARY_ASSETS_URL}discoverSearch.WEBP` },
  discoverFlatList: { uri: `${CLOUDINARY_ASSETS_URL}discoverFlatList.WEBP` },
  discoverFlatListSec: { uri: `${CLOUDINARY_ASSETS_URL}discoverFlatList3.WEBP` },

  // Comment Bar ICONS
  commentCamera: { uri: `${CLOUDINARY_ASSETS_URL}Icons/CommentCameraIcon.WEBP` },
  commentGallery: { uri: `${CLOUDINARY_ASSETS_URL}Icons/CommentGalleryIcon.WEBP` },
  commentGif: { uri: `${CLOUDINARY_ASSETS_URL}Icons/CommentGifIcon.WEBP` },
  notifyIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/bell.WEBP` },

  // Add Note Icon
  addNote: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addNoteIcon.WEBP` },
  addNoteII: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addNoteIconII.WEBP` },
  recordingAnimation: { uri: `${CLOUDINARY_ASSETS_URL}recordingAnimation.gif` },
  stopRecording: { uri: `${CLOUDINARY_ASSETS_URL}stopRecording.WEBP` },
  audioRecording: { uri: `${CLOUDINARY_ASSETS_URL}audioRecording.png` },
  soundFrequency: { uri: `${CLOUDINARY_ASSETS_URL}soundFrequency.WEBP` },
  recordAudioLightPink: { uri: `${CLOUDINARY_ASSETS_URL}recordAudioLightPink.WEBP` },

  microphone: { uri: `${CLOUDINARY_ASSETS_URL}Icons/microphone.WEBP` },
  sendPurpleIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendPurpleIcon.WEBP` },
  redTrashIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/redTrashIcon.WEBP` },

  // Speaker Icon
  speakerIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/SpeakerIcon.WEBP` },
  // Sound Wave Icon
  soundWavesIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/soundWaves.WEBP` },
  // Feed Notes Icon
  feedNotesIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/FeedNotesIcon.WEBP` },
  // Feed Notes Icon
  playAudioIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/playAudioIcon.WEBP` },
  // Audio Play Wave
  notesAudioPlaying: { uri: `${CLOUDINARY_ASSETS_URL}Icons/NotesAudioPlayIcon.WEBP` },
  // Audio Pause Icon
  notesAudioPauseIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/recordAudioPauseIcon.WEBP` },

  // Privacy Icon for Collections
  privacyCollectionsIcon: { uri: `${CLOUDINARY_ASSETS_URL}privacyCollectionsIcon.WEBP` },
  // Collection More Icon in Collection Feed
  collectionMore: { uri: `${CLOUDINARY_ASSETS_URL}Icons/collectionMore.WEBP` },
  // blueCamera: {uri : `${CLOUDINARY_ASSETS_URL}Icons/blueCamera.png`},
  blueCamera: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blueCamera2.WEBP` },
  blackImageIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blackImageIcon.WEBP` },
  blackGifIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Vector_1_ngnzdp.WEBP` },
  plusCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons/pluscircle.WEBP` },
  blackCameraIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blackCameraIcon.WEBP` },

  editCollection: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editCollection.WEBP` },
  collectionPrivacySetting: { uri: `${CLOUDINARY_ASSETS_URL}Icons/collectionPrivacySetting.WEBP` },
  collectionMoveDeleteIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/collectionMoveDeleteIcon.WEBP` },
  deleteCollection: { uri: `${CLOUDINARY_ASSETS_URL}Icons/deleteCollection.WEBP` },

  addUser: { uri: `${CLOUDINARY_ASSETS_URL}addUser.WEBP` },
  addContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/phone.WEBP` },
  contact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_3_pu0jg8.WEBP` },
  whiteAnalogBg: { uri: `${CLOUDINARY_ASSETS_URL}Icons/white-analog-bg.WEBP` },
  fingerPrint: { uri: `${CLOUDINARY_ASSETS_URL}fingerPrint.WEBP` },

  // settings
  account1: { uri: `${CLOUDINARY_ASSETS_URL}settings/account.WEBP` },
  archive1: { uri: `${CLOUDINARY_ASSETS_URL}settings/archive.WEBP` },
  availability: { uri: `${CLOUDINARY_ASSETS_URL}settings/availability.WEBP` },
  away: { uri: `${CLOUDINARY_ASSETS_URL}settings/away.WEBP` },
  offline: { uri: `${CLOUDINARY_ASSETS_URL}settings/offline.WEBP` },
  online: { uri: `${CLOUDINARY_ASSETS_URL}settings/online.WEBP` },
  feedback: { uri: `${CLOUDINARY_ASSETS_URL}settings/feedback.WEBP` },
  help: { uri: `${CLOUDINARY_ASSETS_URL}settings/help.WEBP` },
  invite: { uri: `${CLOUDINARY_ASSETS_URL}settings/invite.WEBP` },
  language: { uri: `${CLOUDINARY_ASSETS_URL}settings/language.WEBP` },
  logout: { uri: `${CLOUDINARY_ASSETS_URL}settings/logout.WEBP` },
  notification1: { uri: `${CLOUDINARY_ASSETS_URL}settings/notification.WEBP` },
  privacy: { uri: `${CLOUDINARY_ASSETS_URL}settings/privacy.WEBP` },
  quickAddTemplate: { uri: `${CLOUDINARY_ASSETS_URL}settings/quickAddTemplate.WEBP` },
  timeFormat1: { uri: `${CLOUDINARY_ASSETS_URL}settings/timeFormat.WEBP` },
  videoCall: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/videoCall.WEBP` },
  redCrossCircled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/cross-red-circle.WEBP` },
  greenCheckCircled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/check-green-circle.WEBP` },

  // Edit Profile
  editProfileFirstNameIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editProfileFirstNameIcon.WEBP` },
  editProfilePhone: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editProfilePhone.WEBP` },
  editProfileAnalogID: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editProfileAnalogID.WEBP` },
  editProfileBirthday: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editProfileBirthday.WEBP` },
  editProfileOccupation: { uri: `${CLOUDINARY_ASSETS_URL}Icons/EditProfileOccupation.WEBP` },
  analogId: { uri: `${CLOUDINARY_ASSETS_URL}analogId.WEBP` },

  // Registration Steps Upload
  registrationStepsUpload: { uri: `${CLOUDINARY_ASSETS_URL}Icons/RegistrationStepsUpload.WEBP` },
  blackBellIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blackBellIcon.WEBP` },
  circlePlusIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/circlePlusIcon.WEBP` },
  searchBlackIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/searchBlackIcon.WEBP` },
  lampIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/lampIcon.WEBP` },
  addContactIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addContact.WEBP` },
  tickIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/tickIcon.WEBP` },
  streamAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/streamAnalogs.WEBP` },
  greyDots: { uri: `${CLOUDINARY_ASSETS_URL}greyDots.WEBP` },
  editNote: { uri: `${CLOUDINARY_ASSETS_URL}editNote.WEBP` },
  deleteNote: { uri: `${CLOUDINARY_ASSETS_URL}deleteNote.WEBP` },

  blockContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blockContact.WEBP` },
  removeContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons/removeContact.WEBP` },

  contactAnalogIDIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/IDIcon.WEBP` },
  fingerPrintIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/finger-prints_1_rd8d5n.WEBP` },
  searchIconI: { uri: `${CLOUDINARY_ASSETS_URL}Icons/search_2_1_jg0mky.WEBP` },
  frequencyAnimation: { uri: `${CLOUDINARY_ASSETS_URL}frequencyAnimation.WEBP` },

  // FirstTime Analog Success Modal
  firstTimerAnalogSuccess: { uri: `${CLOUDINARY_ASSETS_URL}Icons/firstTimeAnalogSuccess.WEBP` },
  guideImageTimer: { uri: `${CLOUDINARY_ASSETS_URL}Icons/guideImageTimer.WEBP` },
  guideImageProfile: { uri: `${CLOUDINARY_ASSETS_URL}Icons/guideImageProfile.WEBP` },

  // Allow Location
  allowLocation: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/allowLocation.WEBP` },

  // Localized Feed Permission
  localizedFeedPermission: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/localizedFeedPermission.WEBP` },
  // On Boarding Notification
  onBoardingNotification: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/notification.WEBP` },
  // No Search Data Found Image
  noDataFoundImage: { uri: `${CLOUDINARY_ASSETS_URL}Icons/noDataFoundImage.WEBP` },

  checkCircle: { uri: `${CLOUDINARY_ASSETS_URL}checkCircle.png` },
  timeChangeReq: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/timeChangeReq.WEBP` },
  chat: { uri: `${CLOUDINARY_ASSETS_URL}Icons/chatIcon.WEBP` },

  recurringSheetIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/recurringSheetIcon.WEBP` },
  commentsSettingIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/CommentsSettingIcon.WEBP` },
  bigPlus: { uri: `${CLOUDINARY_ASSETS_URL}Icons/bigPlus.WEBP` },
  editComment: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editComment.WEBP` },
  copyLink: { uri: `${CLOUDINARY_ASSETS_URL}Icons/copyLink.WEBP` },

  // Feed status
  ended: { uri: `${CLOUDINARY_ASSETS_URL}FeedStatus/ended.WEBP` },

  blockUser: { uri: `${CLOUDINARY_ASSETS_URL}Icons/blockUser.WEBP` },
  sendAMessage: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendAMessage.WEBP` },
  assignSoundReminder: { uri: `${CLOUDINARY_ASSETS_URL}Icons/assignSoundReminder.WEBP` },
  butterfly: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/butterfly.WEBP` },
  colors: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/colors.WEBP` },
  fog: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/fog.WEBP` },
  leaves: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/leaves.WEBP` },
  mountains: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/mountains.WEBP` },
  plants: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/plants.WEBP` },
  rainbow: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/rainbow.WEBP` },
  snow: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/snow.WEBP` },
  snowMountains: { uri: `${CLOUDINARY_ASSETS_URL}Backgrounds/snowMountains.WEBP` },

  messageCopy: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/copy.WEBP` },
  messageReply: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/reply.WEBP` },
  messageStar: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/star.WEBP` },
  messageTrash: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/trash.WEBP` },
  messageForward: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/forward.WEBP` },
  safari: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/safari.WEBP` },
  chrome: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chrome.WEBP` },
  copyLinkMessage: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/copyLink.WEBP` },
  linkedChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons/copyLink.WEBP` },
  checkIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/check.WEBP` },
  nagIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/nagIcon.WEBP` },
  forwarded: { uri: `${CLOUDINARY_ASSETS_URL}Icons/forwarded.WEBP` },
  cloudUpload: { uri: `${CLOUDINARY_ASSETS_URL}Icons/cloudUpload.WEBP` },
  chatCrossIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/chatCrossIcon.WEBP` },

  phoneSmall: { uri: `${CLOUDINARY_ASSETS_URL}Icons/phoneSmall.WEBP` },
  cancelSmall: { uri: `${CLOUDINARY_ASSETS_URL}Icons/cancelSmall.WEBP` },

  addChatContact: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/addContact.WEBP` },
  clearChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/clearChat.WEBP` },
  deleteChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/delete.WEBP` },
  exportChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/exportChat.WEBP` },
  muteChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/mute.WEBP` },
  expandI: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/expand.WEBP` },
  arrowUpRight: { uri: `${CLOUDINARY_ASSETS_URL}Icons/arrow-up-right1.WEBP` },

  moreHorizontalDots: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/moreHorizontalDots.WEBP` },
  archiveChat: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/archiveChat.WEBP` },
  closeReply: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/closeReply.WEBP` },
  stopWatch: { uri: `${CLOUDINARY_ASSETS_URL}Icons/stopWatch.WEBP` },
  stopWatchIII: { uri: `${CLOUDINARY_ASSETS_URL}Icons/stopwatchIII.WEBP` },
  clockTemplate: { uri: `${CLOUDINARY_ASSETS_URL}Icons/clockTemplate.WEBP` },
  editTemplate: { uri: `${CLOUDINARY_ASSETS_URL}Icons/editTemplate.WEBP` },

  // Chat Icons
  gifImage: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/gifImage.WEBP` },
  chatTick: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chatTick.WEBP` },
  chatCamera: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chatCamera.WEBP` },
  chatVideo: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chatVideo.WEBP` },
  chatAudio: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chatAudio.WEBP` },

  sliderIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/slider.WEBP` },
  chatSticker: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/chatSticker.WEBP` },

  starredMessage: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/starredMessages.WEBP` },
  mediaLinks: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/mediaLinks.WEBP` },
  chatSearch: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/chatSearch.WEBP` },
  muteUser: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/muteChat.WEBP` },
  customTone: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/customTone.WEBP` },
  saveToCameraRoll: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/saveToCameraRoll.WEBP` },
  groupInCommons: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/groupsInCommon.WEBP` },
  contactDetails: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/contactDetails.WEBP` },
  blockRed: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/block.WEBP` },
  reportRed: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/reportFlag.WEBP` },
  hollowCrossCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/hollowCrossCircle.WEBP` },
  addGroupCover: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/addGroupCover.WEBP` },
  addDocument: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/addDocument.WEBP` },
  linkToProfile: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/externalLink.WEBP` },

  // Ribben Icons
  ribbenLocation: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenLocation.WEBP` },
  ribbenBell: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenBell.WEBP` },
  ribbenImage: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenImage.WEBP` },
  ribbenUser: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenUser.WEBP` },
  ribbenClock: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenClock.WEBP` },
  ribbenLock: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenLock.WEBP` },
  ribbenShare: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenNetwork.WEBP` },
  ribbenFacebook: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/facebook.WEBP` },
  ribbenRepeat: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/ribbenRepeat.WEBP` },
  ribbenLinkAnalog: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/link-analog.WEBP` },
  documentIcon: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/document.WEBP` },
  LocationIcon: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/location.WEBP` },
  userIcon: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/user.WEBP` },
  nagMe: { uri: `${CLOUDINARY_ASSETS_URL}RibbenIcons/bell.WEBP` },

  // AppStyles
  shopertinoLogo: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/app-logo.WEBP` },
  boederImgSend: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/borderImg1.WEBP` },
  boederImgReceive: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/borderImg2.WEBP` },
  textBoederImgSend: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/textBorderImg1.WEBP` },
  textBoederImgReceive: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/textBorderImg2.WEBP` },
  chat_icon: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/chat.WEBP` },
  file: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/file.WEBP` },
  like_icon: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/like.WEBP` },
  notification_icon: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/notification.WEBP` },
  photo: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/photo.WEBP` },
  pin: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/pin.WEBP` },
  video: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/video.WEBP` },
  audio: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/audio.WEBP` },
  audioPlay_icon: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/audioPlay.WEBP` },
  videoPlay: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/videoPlay.WEBP` },
  clock_icon: { uri: `${CLOUDINARY_ASSETS_URL}Images_sm/clock.WEBP` },

  // AppStyles iconset
  menuHamburger: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/menu-hamburger.WEBP` },
  homeUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/home-unfilled.WEBP` },
  homefilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/home-filled.WEBP` },
  search_icon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/search.WEBP` },
  magnifier: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/magnifier.WEBP` },
  commentUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/comment-unfilled.WEBP` },
  commentFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/comment-filled.WEBP` },
  friendsUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/friends-unfilled.WEBP` },
  friendsFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/friends-filled.WEBP` },
  profileUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/profile-unfilled.WEBP` },
  camera_icon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/camera.WEBP` },
  cameraFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/camera-filled.WEBP` },
  inscription: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/inscription.WEBP` },
  more: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/more.WEBP` },
  send: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/send.WEBP` },
  pinpoint: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/pinpoint.WEBP` },
  checked_icon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/checked.WEBP` },
  bell_icon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/bell.WEBP` },
  surprised: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/wow.WEBP` },
  laugh: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/crylaugh.WEBP` },
  cry: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/crying.WEBP` },
  thumbsupUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/thumbsup-unfilled.WEBP` },
  heartUnfilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/heart-unfilled.WEBP` },
  like_icon_sm: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/blue-like.WEBP` },
  love: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/red-heart.WEBP` },
  angry: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/anger.WEBP` },
  cameraRotate: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/camera-rotate.WEBP` },
  libraryLandscape: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/library-landscape.WEBP` },
  userIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/userIV.WEBP` },
  cameraIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/cameraIV.WEBP` },
  galleryIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/photoVideo.WEBP` },
  addIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/addIV.WEBP` },
  gifIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/gifIV.WEBP` },
  documentIV: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/documentIV.WEBP` },
  unarchiveBlack: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/unarchiveBlack_os16cv.WEBP` },
  cancelBlack: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/cancelBlack_opnk0h.WEBP` },
  versionHistoryBlack: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/versionHistoryBlack_fjt6za.WEBP` },

  // Video Player
  top_vignette: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/top-vignette.WEBP` },
  back: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-back.WEBP` },
  volume: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-volume.WEBP` },
  shrink: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-shrink.WEBP` },
  expand: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-expand.WEBP` },
  bottom_vignette: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-vignette.WEBP` },
  play: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/play.WEBP` },
  pause: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/bottom-pause.WEBP` },
  loader_icon: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/loader-icon.WEBP` },
  error_icon: { uri: `${CLOUDINARY_ASSETS_URL}VideoPlayer/error-icon.WEBP` },

  // Starred Images
  starFilled: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/starFilled_qpuq8f.WEBP` },
  starGreyOutline: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/starGrey_nyix8n.WEBP` },
  starBlackOutline: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/starBlack_rmbggt.WEBP` },

  // Default Images
  noData: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/noData.png` },
  deeplinkLogo: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/AnalogLogo.png` },
  welcomeIII: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/welcomeIII.png` },
  purpleCircledTick: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/purpleCircledTick.png` },
  greyCircledAdd: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/greyCircledAdd.png` },
  email: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/email.png` },
  goldenStar: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/goldenStar.png` },
  noteAudio: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/audioIcon.png` },
  defaultUser: require('../images/defaultIcons/defaultUser.png'),
  pinAnalog: require('../images/defaultIcons/pinAnalog.png'),
  pinAnalogGolden: require('../images/defaultIcons/pinAnalogGolden.png'),
  createFeedPink: require('../images/defaultIcons/createFeedPink.png'),
  defaultImage: require('../images/defaultIcons/default.png'),
  groupTabIcon: require('../images/defaultIcons/groupTabIcon.png'),
  profileFilled: require('../images/defaultIcons/profile-filled.png'),
  profileSorts: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/profileSorts.png` },
  groupDefault: require('../images/defaultIcons/groupDefault.png'),
  defaultSingleUser: require('../images/defaultIcons/defaultSingleUser.png'),
  pencilHollow: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/pencilHollow.png` },
  aboutPrivacy: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/aboutPrivacy.png` },
  personalDetails: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/personalDetails.png` },
  reviewPropose: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/reviewPropose.png` },
  knowGoingOn: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/knowGoingOn.png` },
  addToSpectrum: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/addToSpectrum.png` },
  addSpectrumFriend: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/addSpectrumFriend.png` },
  improveExperience: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/improveExperience.png` },
  userLine: { uri: `${CLOUDINARY_ASSETS_URL}Icons/userLine.png` },
  nagMeTap: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/tagIcon_u43rac.WEBP` },

  // Add-ons
  sunriseSunset: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Mask_Group_1_xc4g8j.WEBP` },

  // Accessory Icons
  media: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_tq22qw.WEBP` },
  gifIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_2_qyo7qa.WEBP` },
  location: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_8_w9bfl0.WEBP` },
  cameraI: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_7_meymli.WEBP` },
  document: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_6_ttp4ft.WEBP` },
  contactI: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_5_kcvbl3.WEBP` },
  emojiI: { uri: `${CLOUDINARY_ASSETS_URL}Icons/Group_1452_4_vsog1w.WEBP` },
  addAnalog: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addAnalog_azj2f7.WEBP` },
  descriptionIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/descriptionIcon_wab4hu.WEBP` },

  trashGrey: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/trashGrey_ecolge.WEBP` },
  trashRed: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/trashRed_ibdfqb.WEBP` },
  arrowDownCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/arrowDown_iqmooe.WEBP` },
  genderIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/gender_mtcfsn.WEBP` },

  doubleTicks: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/doubleTicks_srjhk2.WEBP` },

  plusCircleBlack: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/plusCircleBlack_fy0atp.WEBP` },
  plusCircleWhite: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/plusCircleWhite_djv3wz.WEBP` },
  photoCameraBlack: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/photoCameraBlack_mgidar.WEBP` },
  sticker: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/sticker_vpcpds.WEBP` },
  microphoneBlack: { uri: `${CLOUDINARY_ASSETS_URL}MessageIcons/microphoneBlack_e73szb.WEBP` },
  filterIcon: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/filterIcon.png` },
  addCircleBold: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/addCircleBold.png` },
  locationIcon: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/locationIcon.png` },
  convertedVideo: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/convertedVideo.png` },
  sortIcon: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/sortIcon.png` },
  linkAnalog: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/linked-analog-grey.png` },
  linesHorizontal: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/linesHorizontal.png` },
  addNoteGrey: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/addNoteGrey.png` },
  crossGrey: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/crossGrey.png` },
  turnOffComment: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/turnOffComment.png` },
  turnOnComment: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/turnOnComment.png` },
  editProposal: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/editProposal.png` },
  locationWhite: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/location.png` },
  resend: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/resend.png` },
  chatTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/chatTour.png` },
  spectrumTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/spectrumTour.png` },
  feedTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/feedTour.png` },
  chatTourII: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/chatTourII.png` },
  discoverTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/discoverTour.png` },
  searchTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/searchTour.png` },
  networkTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/networkTour.png` },
  unhideGrey: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/unhideGrey.png` },
  unhide: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/unhide.png` },
  createTour: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/createTour.png` },
  linkAnalogDark: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/link-analog-greyII.png` },
  groupUserIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/userGroup_lgstgr.WEBP` },
  noAnalog: { uri: `${CLOUDINARY_ASSETS_URL}FeedStatus/noAnalogFound_jd9yjk.WEBP` },
  onBoardingTag: { uri: `${CLOUDINARY_ASSETS_URL}OnBoarding/onBoardingTag_nlxi4n.WEBP` },
  unArchiveAnalog: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/unarchiveBlack_os16cv.WEBP` },
  sun: { uri: `${CLOUDINARY_ASSETS_URL}Tabs/integration.png` },
  newCloseCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons/newCloseCircle_zjb86w.WEBP` },
  disconnectSunrise: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/disconnected-chains_ua9sse.WEBP` },
  holidaysIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/holidays_jc60tt.WEBP` },
  holidaysAnalogIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/Mask_Group_vimfya.WEBP` },
  recentDescriptions: { uri: `${CLOUDINARY_ASSETS_URL}Icons/recentDescription_enkl7y.WEBP` },
  tagPeople: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/tagPeople_z8nzb7.WEBP` },

  // Duration Icon
  durationIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/duration_iopg8i.WEBP` },

  // Report Comment Icon
  reportComment: { uri: `${CLOUDINARY_ASSETS_URL}Icons/report.WEBP` },
  deleteComment: { uri: `${CLOUDINARY_ASSETS_URL}Icons/deleteComment.WEBP` },
  slack: { uri: `${CLOUDINARY_ASSETS_URL}Icons_sm/slack_wealuz.WEBP` },
  reactionsIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/reactions.WEBP` },
  plusCirclePink: { uri: `${CLOUDINARY_ASSETS_URL}Icons/plusCirclePink.WEBP` },
  defaultUserImage: `${CLOUDINARY_ASSETS_URL}Icons_sm/profile-filled.WEBP`,
  myProfileAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/myProfileAnalogs.WEBP` },
  birthdayCake: { uri: `${CLOUDINARY_ASSETS_URL}Icons/birthdayCake_ykd4yl.WEBP` },
  gmailAddOn: { uri: `${CLOUDINARY_ASSETS_URL}Icons/gmail_dbqbxr.WEBP` },
  arrowLeftII: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/arrowLeft.png` },
  arrowRightII: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/arrowRight.png` },
  chatArchivedAnalog: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/chatArchivedAnalog.png` },
  profileCombinedAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/profileCombinedAnalogs.WEBP` },
  hiddenAnalogs: { uri: `${CLOUDINARY_ASSETS_URL}Icons/hiddenAnalogsIcon.WEBP` },
  analogCreatorsMarket: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/analogCreatorsMarket.WEBP` },
  coins: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/coins.WEBP` },
  rightArrowIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/rightArrowIcon.WEBP` },
  videoPreviewOne: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/videoPreviewOne.WEBP` },
  videoPreviewTwo: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/videoPreviewTwo.WEBP` },
  myVideo: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/video.WEBP` },
  deleteBlackIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/deleteBlackIcon.WEBP` },
  history: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/history.WEBP` },
  playButton: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/playButton.WEBP` },
  convertedFromAnalog: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/convertedFromAnalog.WEBP` },
  favorites: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/favorites.WEBP` },
  videoPreviewThree: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/videoPreviewThree.WEBP` },
  facebookCircleIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/facebookIcon.WEBP` },
  twitterCircleIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/twitterIcon.WEBP` },
  instagramCircleIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/instagramIcon.WEBP` },
  linkedInCircleIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/linkedInIcon.WEBP` },
  tumblrCircleIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/tumblr.WEBP` },
  release1: { uri: `${CLOUDINARY_ASSETS_URL}ReleaseInfo/release1_usfrd4.WEBP` },
  release2: { uri: `${CLOUDINARY_ASSETS_URL}ReleaseInfo/release2_g8zcpv.WEBP` },
  myLibrary: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/myLibrary.WEBP` },
  dummyImage: { uri: `${CLOUDINARY_ASSETS_URL}Icons/dummy.png` },
  cameraIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/cameraGreyIcon.png` },
  convertVideoIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/covertVideoIcon.png` },
  analogMarketVideoDefault: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/analogMarketVideoDefault.png` },
  circledChatTick: { uri: `${CLOUDINARY_ASSETS_URL}defaultIcons/blue-circled-tick.png` },
  scanImag: { uri: `${CLOUDINARY_ASSETS_URL}Icons/qr-code-scan.png` },
  helpCircle: { uri: `${CLOUDINARY_ASSETS_URL}Icons/help-circle.png` },
  reGenerate: { uri: `${CLOUDINARY_ASSETS_URL}Icons/multimedia-Regenerate.png` },
  purpleDownloadIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/downloadPurple.png` },
  sharePurpleIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sharePurple.png` },
  groupIcon: { uri: `${CLOUDINARY_ASSETS_URL}Groups/groupIcon.WEBP` },
  copyPinkIcon: `${CLOUDINARY_ASSETS_URL}Groups/copyPinkIcon.WEBP`,
  messagePinkIcon: `${CLOUDINARY_ASSETS_URL}Groups/messagePinkIcon.WEBP`,
  groupBlueUserIcon: { uri: `${CLOUDINARY_ASSETS_URL}Groups/groupUserIcon.WEBP` },
  GroupCoverImage: { uri: `${CLOUDINARY_ASSETS_URL}Groups/coverImage.WEBP` },

  trashDelete: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/trashdelete.WEBP` },
  shareIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/share.WEBP` },
  filePlusIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/fileplusIcon.WEBP` },
  listIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/listIcon.WEBP` },
  downloadIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/download.WEBP` },
  addToListIcon: { uri: `${CLOUDINARY_ASSETS_URL}AnalogMarket/addToList.WEBP` },

  addDescription: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addDescription.WEBP` },
  geryPlus: { uri: `${CLOUDINARY_ASSETS_URL}Icons/geryPlus.WEBP` },
  inviteMembers: { uri: `${CLOUDINARY_ASSETS_URL}Icons/inviteMembers.WEBP` },
  addCover: { uri: `${CLOUDINARY_ASSETS_URL}Icons/addCover.WEBP` },
  doubleUser: { uri: `${CLOUDINARY_ASSETS_URL}Icons/doubleUser.WEBP` },
  privacyIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/privacyIcon.WEBP` },
  historyIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/historyIcon.WEBP` },
  hiddenIcon: { uri: `${CLOUDINARY_ASSETS_URL}Icons/hiddenIcon.WEBP` },
  createdAt: { uri: `${CLOUDINARY_ASSETS_URL}Icons/createdAt.WEBP` },
  sendNotify: { uri: `${CLOUDINARY_ASSETS_URL}Icons/sendNotify.WEBP` },

  theatre: `${CLOUDINARY_ASSETS_URL}GroupCategories/theatre.WEBP`,
  drinks: `${CLOUDINARY_ASSETS_URL}GroupCategories/drinks.WEBP`,
  sports: `${CLOUDINARY_ASSETS_URL}GroupCategories/sports.WEBP`,
  games: `${CLOUDINARY_ASSETS_URL}GroupCategories/games.WEBP`,
  crafts: `${CLOUDINARY_ASSETS_URL}GroupCategories/crafts.WEBP`,
  networking: `${CLOUDINARY_ASSETS_URL}GroupCategories/networking.WEBP`,
  shopping: `${CLOUDINARY_ASSETS_URL}GroupCategories/shopping.WEBP`,
  hobby: `${CLOUDINARY_ASSETS_URL}GroupCategories/hobby.WEBP`,
  dance: `${CLOUDINARY_ASSETS_URL}GroupCategories/dance.WEBP`,
  religion: `${CLOUDINARY_ASSETS_URL}GroupCategories/religion.WEBP`,
  party: `${CLOUDINARY_ASSETS_URL}GroupCategories/party.WEBP`,
  natural: `${CLOUDINARY_ASSETS_URL}GroupCategories/natural.WEBP`,
  home: `${CLOUDINARY_ASSETS_URL}GroupCategories/home.WEBP`,
  travelling: `${CLOUDINARY_ASSETS_URL}GroupCategories/travelling.WEBP`,
  art: `${CLOUDINARY_ASSETS_URL}GroupCategories/art.WEBP`,
  wellness: `${CLOUDINARY_ASSETS_URL}GroupCategories/wellness.WEBP`,
  literature: `${CLOUDINARY_ASSETS_URL}GroupCategories/literature.WEBP`,
  food: `${CLOUDINARY_ASSETS_URL}GroupCategories/food.WEBP`,
  film: `${CLOUDINARY_ASSETS_URL}GroupCategories/film.WEBP`,
  healthy: `${CLOUDINARY_ASSETS_URL}GroupCategories/healthy.WEBP`,
  comedy: `${CLOUDINARY_ASSETS_URL}GroupCategories/comedy.WEBP`,
  causes: `${CLOUDINARY_ASSETS_URL}GroupCategories/causes.WEBP`,
  other: `${CLOUDINARY_ASSETS_URL}GroupCategories/other.WEBP`,
  gardening: `${CLOUDINARY_ASSETS_URL}GroupCategories/gardening.WEBP`,
  health: `${CLOUDINARY_ASSETS_URL}GroupCategories/health.WEBP`,
  music: `${CLOUDINARY_ASSETS_URL}GroupCategories/music.WEBP`,
  animals: `${CLOUDINARY_ASSETS_URL}GroupCategories/animals.WEBP`,
  fitness: `${CLOUDINARY_ASSETS_URL}GroupCategories/fitness.WEBP`,
  finance: `${CLOUDINARY_ASSETS_URL}GroupCategories/finance.WEBP`,
  travel: `${CLOUDINARY_ASSETS_URL}GroupCategories/travel.WEBP`,

  whiteFilterIcon: `${CLOUDINARY_ASSETS_URL}Notes/whiteFilterIcon.png`,

  memberRequest: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/memberRequest.WEBP` },
  removeBlock: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/removeBlock.WEBP` },
  leaveGroup: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/leaveGroup.WEBP` },
  memberQuestion: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/memberQuestion.WEBP` },
  checkBox: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/checkBox.WEBP` },
  rulesIcon: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/rulesIcon.WEBP` },
  changeCoverPhoto: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/changeCoverPhoto.WEBP` },
  cancelInvitation: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/cancelInvitation.WEBP` },
  refreshHistory: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/refreshHistory.WEBP` },
  sortedMembers: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/sortedMembers.WEBP` },
  descriptionHistory: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/descriptionHistory.WEBP` },
  createdHistory: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/createdHistory.WEBP` },
  editGroupDescription: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/editGroupDescription.WEBP` },
  createdGroup: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/createdGroup.WEBP` },
  ruleMainIcon: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/ruleMainIcon.WEBP` },
  multipleQuestion: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/multipleQuestion.WEBP` },
  writeAnswer: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/writeAnswer.WEBP` },
  archriveGroup: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/archriveGroup.WEBP` },
  viewProfile: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/viewProfile.WEBP` },
  unmute: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/unmute.WEBP` },
  individualAccound: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/individualAccound.WEBP` },
  purpleGroupDetails: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/purpleGroupDetails.WEBP` },
  purpleGroupDescription: { uri: `${CLOUDINARY_ASSETS_URL}GroupToolsIcon/purpleGroupDescription.WEBP` },

  sunsetSunrise: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/sunsetSunrise.WEBP` },
  zoom: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/zoom.WEBP` },
  weather: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/weather.WEBP` },
  slackII: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/slack.WEBP` },
  purpleWork: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleWork.WEBP` },
  purpleTime: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleTime.WEBP` },
  purpleUser: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleUser.WEBP` },
  purpleTick: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleTick.WEBP` },
  purpleTab: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleTab.WEBP` },
  purpleShare: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleShare.WEBP` },
  purpleRightArrow: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleRightArrow.WEBP` },
  purpleSun: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleSun.WEBP` },
  purpleShare_2: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleShare_2.WEBP` },
  purpleOrbit: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleOrbit.WEBP` },
  purpleNotify: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleNotify.WEBP` },
  purpleMagnifyingGlass: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleMagnifyingGlass.WEBP` },
  purpleGroup: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleGroup.WEBP` },
  purpleSubsteps: require('../images/defaultIcons/purpleSubsteps.png'),
  purpleMsg: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleMsg.WEBP` },
  purpleNetwork: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleNetwork.WEBP` },
  purpleDoc: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleDoc.WEBP` },
  purpleEye: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleEye.WEBP` },
  purpleClock: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleClock.WEBP` },
  purplecClip: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purplecClip.WEBP` },
  purpleChat: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleChat.WEBP` },
  nounConnection_584128: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/nounConnection_584128.WEBP` },
  airQuality: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/airQuality.WEBP` },
  purpleCancel: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleCancel.WEBP` },
  purpleCalender: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleCalender.WEBP` },
  chromeII: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/chrome.WEBP` },
  purpleAnalogLogo: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleAnalogLogo.WEBP` },
  birthdayII: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/birthday.WEBP` },
  purpleBell: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purpleBell.WEBP` },
  gmailIV: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/gmailIV.WEBP` },
  holidaysII: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/holidaysII .WEBP` },

  sunriseII: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/sunriseII.WEBP` },
  sunsetSunriseBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/sunsetSunriseBold.WEBP` },
  zoomBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/zoom.WEBPBold` },
  weatherBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/weatherBold.WEBP` },
  slackIIBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/slack.WEBPBold` },
  purpleWorkBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/businessAccountBold.WEBP` },
  purpleTimeBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/upcommingAnalogBold.WEBP` },
  purpleUserBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/groupsBold.WEBP` },
  purpleTickBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/checkMarkBold.WEBP` },
  purpleTabBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/innerCliquesBold.WEBP` },
  purpleShareBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/shareBold.WEBP` },
  purpleRightArrowBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/shareProfileBold.WEBP` },
  purpleSunBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/purposeAnalogBold.WEBP` },
  purpleShare_2Bold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/startFromPastBold.WEBP` },
  purpleOrbitBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/addToSpectrumBold.WEBP` },
  purpleNotifyBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/nagMeBold.WEBP` },
  purpleMagnifyingGlassBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/explorePageBold.WEBP` },
  purpleGroupBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/subStepsBold.WEBP` },
  purpleMsgBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/messageBold.WEBP` },
  purpleNetworkBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/discoverBold.WEBP` },
  purpleDocBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/notesBold.WEBP` },
  purpleEyeBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/snoozeBold.WEBP` },
  purpleClockBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/stopWatchBold.WEBP` },
  purplecClipBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/linkedAnalogBold.WEBP` },
  purpleChatBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/chatBold.WEBP` },
  nounConnection_584128Bold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/nounConnection_584128Bold.WEBP` },
  airQualityBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/airQualityBold.WEBP` },
  purpleCancelBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/blockBold.WEBP` },
  purpleCalenderBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/calenderBold.WEBP` },
  chromeIIBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/chrome.BoldWEBP` },
  purpleAnalogLogoBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/createAnalog.WEBP` },
  birthdayIIBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/birthdayBold.WEBP` },
  purpleBellBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/notificationBold.WEBP` },
  gmailIIBold: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/gmail.WEBPBold` },
  hash: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/hash.WEBP` },
  discoverLocation: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/locationIcon.WEBP` },
  commentAddIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/commentAddIcon.WEBP` },
  bellFillBlackIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/bellFillBlackIcon.WEBP` },
  bellPinkIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/bellPinkIcon.WEBP` },
  bellCancelIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/bellCancelIcon.WEBP` },
  bellFillPinkIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/bellFillPinkIcon.WEBP` },
  bellBlackIcon: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/bellBlackIcon.WEBP` },
  addEmail: { uri: `${CLOUDINARY_ASSETS_URL}suggestedToolTip/addEmail.WEBP` }
}

export default images
